### ISSUE TITLE
Cobblestone Macerator double recipe

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#112]
Somehow cobblestone ended up with two macerator recipes (greg auto-derped somewhere): cobble->sand and cobble->stone dust, and sadly the stone dust is winning. If I could figure out the new format for minetweaker macerator recipes I'd put one here that grove could use.

**Comment by JasonMcRay** [comment]
Should be fixed in v2.0.7(8)

**Comment by Timeslice42** [comment]
The page you linked for GT support is still only showing the GT 4 stuff. There's a fair amount in there that isn't relevant/correct in GT 5.

**Comment by JasonMcRay** [comment]
I am using that page for all my messing with GT recipes and didnt encounter a single issue.

**Comment by Timeslice42** [comment]
That's because Greg kept the API compatible wherever possible, but GT 5 doesn't have an industrial grinder, distillation tower, nor a fusion reactor. And that page doesn't have the methods for all the new GT machines, such as the laser engraver, fluid solidifier, etc.

**Comment by JasonMcRay** [comment]
The wiki has IG, Dt etc because it is used in 1.6.4. And MT is still supporting it. It doesnt have some machines, because the support has not been implemented for those machines.

Here you can see all currently supported machines for GT5: https://github.com/stanhebben/MineTweaker3/tree/master/MineTweaker3-MC1710-Mod-GregTech/src/main/java/minetweaker/mods/gregtech/machines.

And here for example you can see source for adding a recipe. https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-MC1710-Mod-GregTech/src/main/java/minetweaker/mods/gregtech/machines/AlloySmelter.java#L31-L32

So yes, some items will be missing. But you can make the recipes work if you will look at the source.
