### ISSUE TITLE
(minor) Jungle trees not spawning

### ISSUE THREAD

**Issue by Bobblybook** [JasonMcRay/InfiTech-1.7#118]
Jungle trees are not spawning. Have checked both "mini-jungle" and "extreme jungle" biomes.
Both are just filled with oak trees & vines, and the extreme jungle also has massive blue rainbow eucalypts (I believe from EbXL?), but no vanilla jungle trees (or those big vanilla "rubbertrees" either).

Also pam's harvestcraft jungle fruit trees do not spawn (cinnamon, starfruit, durian, various other exotic fruits with jungle base tree). The only "jungle" based tree I have found is coconut, which apparently is coded to spawn on island biomes also (which is where I found mine).

So something is up with trees/spawns within the jungle biomes. I wasn't able to find and check a vanilla "Jungle" biome, only the two above.

**Comment by JasonMcRay** [comment]
Unfortunately there is nothing I can do with the current modpack. MiniJungle and Extreme Jungles are both from extrabiomesXL and it appears that this is fixed in the latest version, but we unfortunately can't update without breaking already generated worlds, because we had alpha version of the mod and I wasnt really expecting that EXBL will get massive breaking update.

Vanilla Jungle biome is fine, i checked it.

Since this is "minor" issue really, I am going to close it without any fix for now.
