### ISSUE TITLE
Division Sigil spawning in Stronghold libraries

### ISSUE THREAD

**Issue by hlaaftana** [JasonMcRay/InfiTech-1.7#149]
I don't know if this was intended, but title explains it.
Just typing the code in so you can just copy paste it: vanilla.loot.removeChestLoot("strongholdLibrary", sigilDivision);

**Comment by JasonMcRay** [comment]
They aren't spawning in any chests because of: https://github.com/JasonMcRay/InfiTech-1.7/blob/master/config/ExtraUtilities.cfg#L136
You might found one in a chest probably because the chest was generated before that has been changed. Those lines in the minetwekaer scripts are not doing anything, they are deprecated
