### ISSUE TITLE
Minechem?

### ISSUE THREAD

**Issue by AiwendilCiunio** [JasonMcRay/InfiTech-1.7#196]
Changelog says it's in the modpack, but NEI shows nothing, just like it was removed. What's the deal with that?

**Comment by JasonMcRay** [comment]
Dont look at the changelog in here. Take a look to changelog on the forum post, it has been removed, because I got annoyed by almost everytime freezing during load. I am keeping an eye on it and already reported that issue. Unfortunately it is long standing issue, but I still have a good faith in Jakimfett (Minechem dev), that he will be able to fix it. If it will be fixed, it will make its return.

Not everyone is having the issue, tho, but some ppl are. I also pinpointed that its probably not something in my PC, because I have recently bought completely new one, and it is still happening.
