### ISSUE TITLE
Modpack being the cause of low TPS

### ISSUE THREAD

**Issue by AiwendilCiunio** [JasonMcRay/InfiTech-1.7#204]
Miguel from our server posted this:

http://infitech.enjin.com/forum/m/26910956/viewthread/22444250-lag-into-modpack

As you may know, we're constantly running with low tps. You said you had a private server. Do you have tps problems there as well?

**Comment by JasonMcRay** [comment]
No problems on my SSP nor server. Maybe try to run opis, to see what is the offending stuff (opis and mobius core needds to be manually enabled).

**Comment by groveham** [comment]
When I was at home this morning I tested it and I was getting very low fps too. My tps never went above 20 and it runs about 70-100tps on v2.2.0 with a world and machines loaded. 

Server is having tps issues as well. Yes there is about 5 people online 24hrs a day but with regular reboots and even after its rebooted with no one logged on yet the tps still hovers around the 10-15 mark. TPS is currently 12 with 9 people online.

Might be a hard issue to pinpoint but I think it's strange that it's happening on both single player and on my server as well as someone else too.

**Comment by AiwendilCiunio** [comment]
Well I suggest installing Opis and studying test results closely. Maybe that helps. If not, I'm afraid the only solution is disabling mods one by one to check which one is causing problems.

If TPS is so low now when people barely have any machines, I'm terrified to even think what will happen when we progress more.

**Comment by JasonMcRay** [comment]
Noone had the issue. I am playing on my private little server hosted on my own, playing with a friend. No lag issue at all.

As for your "harsh words" I understand its annoying and totally unplayable. I announced that I was looking for testers on the FTB forum, thats the main place where I am residing.

Right now the best bet is to at least run opis to see if anything is out of ordinary.

**Comment by groveham** [comment]
OK so, after disabling InfitechCore, server play is MUCH smoother, 8 people online and very little lag if any at all, this is how I'd expect a server to run and it's how it was running before the update.

**Comment by Tyriael-Soban** [comment]
I hate to say it, but im now getting this issue on my laptop playing by myself ... average tick times are holding between 60-200 ms on a brand new world.
thus far my testing skipping between beyond reality and infitech have proved inconclusive, beyond reality has huge framerate issues and has a larger modlist than us - tick times on a sparsely used world (low electrical and steam tech) are 8-20m/s.
Sadly, my laptop takes about 20 mins to load BR and 15 mins to load ITv3 ... (i wont pretend to understand how my laptop is slower than a desktop 6 times its age) and testing from my desktop is out of the question since im between homes right now and have nowhere to set it up.

**Comment by Tyriael-Soban** [comment]
I think i hit gold here chaps, my first test was re-enabling thaumcraft.
at first - the world seemed stable with a tolerable increase to between 20 - 30 ms tick time.

however once i began to explore the tick time skyrocketed to well over 100 ms and although i have since stopped exploring, the average World values for the internal server have not dropped by any significant amount and right now they seem to rest between 50-80 ms.
the console is constantly spamming about skipping ticks regardless of if im currently idle, wandering generated chunks or venturing into chunks that have yet to be generated.
![tpsestworld002](https://cloud.githubusercontent.com/assets/9297841/8247193/3b2d06c2-1609-11e5-9406-ed73f163792a.png)

**Comment by Tyriael-Soban** [comment]
a combination of thaumcraft and its partnering mods, with XBL leave the idle tick speed at 80-120 ms.
while under similar circumstances of load as the previous test, the game has reached a point where i get less than 1/4 of a tick per second.
sadly, i was an idiot and closed the console ...

**Comment by JasonMcRay** [comment]
Hmm.... I have experienced similiar issue yesterday on my personal server. Didnt had time to look at it, but it is certainly an issue. Not sure where its originating from. One time it dropped down to around 15tps with just me and my friend, not exploring. I will try to do some tests when I get home. If you will be able to conduct some testing on your own, it will be much appreciated.

Thanks

**Comment by Tyriael-Soban** [comment]
I'm now taking a second look at the unofficial GT as well as our newest addition bluepower (though it didnt make a difference) and chisel2 
I am actually rather surprised that the pack would even launch without GT.
Asides to a buttload of script errors and journeymap pallet errors, this pack sans GT still hits with a whopping 140 ms on world ticks.
Admittedly, some of the issue could of been due to the fact that my laptop believed it was running on battery power even whilst plugged in ... still, even with all this stuff disabled im barely holding off 50+ ms... this does however mean all of my testing has been tainted, that kids is why i hate using a laptop ...

**Comment by AiwendilCiunio** [comment]
Thats about how much we get with 1-2 players online - 50ms, maybe 53ms. With more players it grows  exponentially.

**Comment by JasonMcRay** [comment]
I am desperatery trying to replicate the issue on my personal server. So far 3 players online and still at full 50ms. Not sure how many clients I will be able to conenct to my 4GB RAM server before it will be cause of Not Enough Memory.

If I will be able to replicate the issue, I should be able to find thge offender via Java Proviler.

**Comment by Tyriael-Soban** [comment]
I just had spikes enough to crash my client in an XBL Temp. Rainforest biome, i do wonder if the issues everyone is getting are related to that?
@groveham - do you have the resources to run two servers in parallel (from the same machine) and test it without XBL? (Mugik always disabled xbl and bop in older pack versions because they made his server dick around)

**Comment by groveham** [comment]
I don't have the server capacity to do that at the moment but soon with a new dedicated server I can test and run a production server at the same time.

**Comment by groveham** [comment]
Ok, dedicated server is up and running and we're experiencing the exact same issues on the dedicated server as we are on the hosted server. The dedicated server rules out hardware/hosting issues. It has to be something in the modpack. @AiwendilCiunio has done some testing (see forum thread) and it's either BluePower or EBXL that's causing the issues. Will try remove Blue Power from the world and test, then will remove EBXL from the world then test. I expect it to break a crap load of stuff....

**Comment by groveham** [comment]
Removing EBXL has a massive improvement to tps and tick time. We've got a good average time going on the Dedicated server after removing EBXL all together. Would mean generating a new world though if we/everyone was to remove it.

**Comment by AiwendilCiunio** [comment]
Jason I did quite a bit of testing and I also found the connection between TC and lag. When I go near a TC biome tps suddenly plummets, whereas outside of them (out of load radius) it stays low. This is almost certainly the problem of low tps on the server, gonna keep looking for a solution.

**Comment by Tyriael-Soban** [comment]
That change from EXBL is exactly what i expected and experienced when i did all that mucking around last week, even though my results were horribly tainted by my power management configuration *rolls eyes.*  
Wandering near anything to do with thaumcraft or EXBL (or worse, both together) causes TPS spikes and MASSIVE framerate spikes in the case of TC - it gets floored to 20 fps, disabling the "special shader" in the TC config dosnt make much of a difference either.

**Comment by AiwendilCiunio** [comment]
Well I managed to pinpoint it to just TC, EBXL doesnt seem to have anything to do with it. I tested without TC and with EBXL and the game run smooth as silk. Before I tested with TC (even tried rerolling to an earlier version) but without EBXL and the problem was still there.

Also Jason can you pin or sticky it so it appears on the top? Because right now it's buried with other posts and probably noone will read that.

**Comment by AiwendilCiunio** [comment]
Last update: It's 95% FastLeaveDecay conflicting with Thaumcraft. See server forum thread for more info.

I think I did it guys :+1:

**Comment by groveham** [comment]
I'm home in around 5 hours. I'll kick off the dedicated server so we can test this en mass :)

**Comment by JasonMcRay** [comment]
@AiwendilCiunio You my friend are completely and fully correct: http://minecraft.curseforge.com/mc-mods/230976-fastleafdecay?comment=3

Would you mind just downgrading FLD mod to 1.1 from that site?

**Comment by Tyriael-Soban** [comment]
6 ms tick time.
<3
