### ISSUE TITLE
Wind Generator

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#239]
The IC2 wind generators still use the vanilla ic2 recipe and are op.
It only requires iron for the machines and you can make it in LV

The rotors only need wood/iron/steel/carbon
steel rotor ~80eu/t and lasts 72hours
carbon rotor ~120eu/t and lasts 168hours (1week) total 1.451.520.000 EU (1,4trillion eu)
(compared to ~2-4 million eu for 1 yellorium in big reactor)

**Comment by AiwendilCiunio** [comment]
I think recipe needs MV extruder, but otherwise yes, I think recipes should be changed.

**Comment by winsomniak** [comment]
Since this nerf post is based on my setup, I figure I better post the details.

120eu/t is peak output at ideal height (160y according to wind meter) with 0 cable loss. Wind fluctuates quite a lot and average output (at ideal height) is closer to 80 or 90 eu for carbon rotor before cable loss. With MV tech, after cable loss I net about 50 per rotor average.

Wind Turbines can't be made in LV as MV extruder is required for shafts.

Building these requires many machines and a large pile of resources.

Infrastructure to support 4 turbines on one pole with the best blades would be as follows:
8 lv transformers for ic2=>gt power (2 per turbine)
2 mv transformers, one at the top accepting from 4 turbines, 1 at bottom to convert back from HV
2 stacks of silver cables to connect the transformers between rotors and from  the pole to the ground
4 Kinetic Generators
4 Kinetic Wind Generators
4 Carbon Blades

Perfect build cost (full suite of LV machines and MV extruder) is as follows
8 LV Transformers
    64 Steel Ingots
    56 Rubber Sheets
    28 Tin Ingot
2 MV Transformers
    16 Aluminium Ingots
    14 Rubber Sheets
     7 Copper Ingots
2 Stacks of Silver Cable
    64 Silver ingots
    128 Rubber Sheets
4 Kinetic Generators
    88 Iron
    32 Stone
    8 Redstone
    8 Battery Alloy
    6 Tin Ingot
    4 Rubber Sheet
    16 Copper Ingot
4 kinetic Wind Generators
    104 Iron
4 Carbon Blades
    576 Carbon
    36 Steel


Total:
192 Iron Ingots
100 Steel Ingots
64 Silver Ingots
34 Tin Ingots
23 Copper Ingots
16 Aluminium Ingots
8 Battery Alloy Ingots
8 Redstone
576 Carbon
202 Rubber Sheets
32  Stone

Exluded costs: tower, platform, ladder, required suite of machines, power to process everything

There is nothing fast or easy or cheap about setting these up. After the above, I get about 200eu/t to fuel my EBF, which was required to build it in the first place.

Comparing renewable energy components (blades) to non-renewable energy fuel is I think a poor metric.  Yellorium has the capacity to output much faster for the structural cost than turbines, as does nitro fuel and other expendable sources of power.

-Winsomniak

**Comment by JasonMcRay** [comment]
I can only change the time they last for ALL of them. Which would make others than Carbon blades bit not worth at all (like wooden blades lasts for couple of minutes (maybe not even that), which is totally idiotic).

Wind Kinetic Gens will be bit more expensive.

**Comment by DarknessShadow** [comment]
"Wood Ring" does not have a recipe -> "Kinetic Gearbox Rotor (Wood)" is uncraftable
(at least my nei doest not show a recipe in sp)
