### ISSUE TITLE
Naquada Generator

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#247]
I think the naquada generator is overpowered.
It is either mk1 2048eu/t or mk2 8192eu/t generator and both can be made with only HV machines.
(mk2 is only slightly more expensive than mk1 making the mk1 useless)
Im still in HV and I have now increased my energy generation by 800% to 9000eu/t generation 
(for comparison making helium plasma in fusion generator needs 4000eu/t)
I think the generator recipes should be changed to be more expensive and only craftable if you are already in EV / IV Age (mk2 after fusion something like helium plasma in recipe)

**Comment by Xavion3** [comment]
The naquadah generator is balanced around the rarity of naquadah, which is really, really rare. It also falls into the non-renewable without bees category as a lot of things, unlike most it only spawns in one really rare vein that only appears in the end. Think of it like plutonium, just because you're lucky in finding some veins it doesn't mean it's common, it's a really rare resource that is not easy to acquire at all.

Also that's generally a thing of the higher machines, once you hit HV tech pretty much any machine tier is available to craft, basically nothing actually requires EV or IV machines for components.

**Comment by winsomniak** [comment]
GIven the amount of setup required for pretty much every other form of  energy generation, I'm inclined to agree with Dark on this one.

Going to the end and flying around is basically all that is required to find this stuff en mass.

For comparison, Jason recently changed wind turbines to require iridium and tungsteel. Why would I ever bother with low energy output turbines in HV, when I can just go fly around the end for some naquada?

Regarding rarity, its the tin problem, you either have an endless supply or none.

**Comment by JasonMcRay** [comment]
Finding Naq in the end is more than jhust rarity problem. in most cases you need to kill dragon, sometimes you will not be able to find a naq vein at all, forcing you to regen the end with Temple Caller.

In this case, I am not going to change this recipe. Wind Turbines were changed because they was generating energy from literaly nothing. Naq gens require resource which is "not unlimited".

**Comment by DarknessShadow** [comment]
1) killing the dragon is in most cases not necessary (because its already dead on a server) 
2) i found 3 naquada veins very quickly (i have now enriched naquada equivalent to 32billion eu)

**Comment by winsomniak** [comment]
Wind turbines were just an example of something (now) in the same voltage tier. You'd need 100 of them to match the mark 2 naq generator. 

Maybe our server isn't typical, but 4 or 5 players had naquada before even reaching HV with the use of things like harness and biogas jetpack. Some people found several large veins of it in fact. The End is allegedly infinite, so no need to regen it.

The problem may not be specifically naqauda's rarity, but the relative ease of finding veins (of anything)in The End due to 3d exposed  stone being essentially everywhere.
