### ISSUE TITLE
Suggestion: recipe for an AE2 inscriber name press

### ISSUE THREAD

**Issue by Ieldra2** [JasonMcRay/InfiTech-1.7#263]
Standard AE2 recipe is
(1) Use an iron ingot in the gui of a quartz cutting knife (r-click empty air with the knife to get there) and input a text string to make an inscriber name tag.
(2) Use that in an inscriber to name items such a storage cells.

Since the quartz cutting knife and the inscriber are both disabled in Infitech, it is currently not possible to make or use inscriber name presses, and thus not possible to name storage modules without expending experience, which I consider implausible. I suggest a recipe to make an inscriber name press using, maybe, an iron plate in an appropriate GT machine, and one to imprint the name on an item using the inscriber name press, maybe in a GT forming press. The first step requires a gui where you can input a text string.

**Comment by JasonMcRay** [comment]
There is no solution how to "imprint" the text/name on the Name Press unfortunately.
But fortunately since I am now able to remove all recipes within Inscriber itself (without causing a crash), I can easily re-enable the Inscriber with Cutting knife.
AE2 Inscriber will be only used for naming.
AE2 Cutting Knife will be only used for making the Name Press

**Comment by JasonMcRay** [comment]
Hmm.. ok removing recipes within Inscriber still causes ocasional crash. Will report it, will implement this IF/WHEN its fixed.
