### ISSUE TITLE
Stargate energy cost

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#282]
A connection from OW to mars only costs around 900k eu for the maximum opening time of 300sec.
Activating the stargate only costs 100k
I think those numbers should be drastically increased
150eu/t is not alot for a stargate

**Comment by JasonMcRay** [comment]
Are you sure about the EU costs? Because the calculations doesnt match both.

Because:
If Stargate consumes 100,000EU for opening cross-dimensionaly.
Config options are
Number of openings per fuel item: 24
Number of minutes open per fuel: 80 minutes
Energy per fuel item: 96,000 SEU (Stargate Energy Units)
Cross-dimensional multiplier: 4.0

So 1 opening in same dimension: 96,000/24 = 4,000 SEU
Opening cross dimensional: 4,000 * 4.0 = 16,000 SEU
So the conversion ratio is 1 SEU = 100,000 / 16,000 = 6,25 EU

Then for the EU/t usage for keep the connection open:
80 minutes = fuel item = 96,000 SEU
96,000 SEU = 96,000 SEU * 6,25 = 600,000EU
600,000 EU / 96,000 ticks = 6,25 EU/t
Cross dimensionaly = 6,25 * 4 = 25 EU/t

It is even lower than you said, but I just want to make sure there arent any internal mod problems.

**Comment by DarknessShadow** [comment]
I didnt look at the configs 
I tested it in sp with a timer and looking at the mfsu
So I just did it again from OW to mars
With a max opening time of 5min 837.632 eu was used.
Opening the wormhole costs 337.920 eu (oops).
After the activation its using 20k eu every 12sec.

5mins = 6000ticks
837.632eu - 337.920eu = 499.712eu
499.712eu / 6000tick = 83 eu/t

Now the opening of the wormhole is 3,3792 times more expensive than I said the first time (sorry).
(3,3792 * 25eu/t = 84,48eu/t)

**Comment by JasonMcRay** [comment]
Thanks that makes more mathematical sense now :)

**Comment by JasonMcRay** [comment]
Ok. So after 3 hours messing with this stupid thing :)

Numbers are approximate. For same dimension.
Activation: 550kEU
Energy used in 5 minutes: 3,5 million EU

For cross dimension it is x3.5
Activation: Roughly 2 million EU
Energy used in 5 minutes: 12.250.000 EU

Also I raised the time the gate will stay open to 7,5 minutes

There is no reason to go higher, since in that time you will have StarGate built, you will have other ways of transport (items via Dimensional Transceiver; player via Galacticraft Rocket for example).

Honestly SGates are mainly just for appearence and showing that you accomplished something. Cost is indeed ridiculously high but hey. Its worth the gate dialing sounds :D

**Comment by DarknessShadow** [comment]
Why did you reduce the sound of the stargate ? on 1 its 15 blocks and on 0.7 the sound only goes 10 blocks.
That means you probably wont hear the stargate at all if you want to make a stargate room with a controll room infront of it.

**Comment by DarknessShadow** [comment]
I hate to say it but the cross dimension multiplier is way too high -.-"

I did some testing in sp to figure out how expensive the connections get with distance.
Those are OW -> OW connection (in EU)
<a href="http://imgur.com/NbU2bs5"><img src="http://i.imgur.com/NbU2bs5.jpg" title="source: imgur.com" /></a>
The energy cost here seems good. The maximum distance is higher than anyone would probably need (70k blocks).

But when we look at the OW -> Mars connections we get the problem :(
<a href="http://imgur.com/Hkecg3N"><img src="http://i.imgur.com/Hkecg3N.jpg" title="source: imgur.com" /></a>
The maximum distance you can travel is now below 1000 blocks which means you can only go to same coords in another dimension and that sucks.

I really wish this mod had a config option to increase the capacity of those Stargate Power things.


This is why I think the cross dimension multiplier needs to be change to a MAXIMUM of 1.5
4million eu cost for a crossdimension connection with a maximum distance of 10k blocks

**Comment by JasonMcRay** [comment]
I see.. I forgot that Range also affects the cross dim connection.
