### ISSUE TITLE
Naquada Alloy for Stargates

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#287]
I think the naquada alloy required for a stargate should get a more expensive recipe.
Right now it is only naquada dust + iron dust in LV chemical reactor for 360keu at 32eu/t and that is cheap.
1 Stargate needs 32 naquada alloy plates

So I think the recipe could be changed to something like:
naquada dust + iridium dust = naquada alloy dust in a MV+ chemical reactor

**Comment by Xavion3** [comment]
Why? The intended cost is the naquadah, the iron isn't really meant to be a cost next to that. If you've got the naquadah you've got what they want pretty much, I mean sure boosting to an MV machine could work but why swap the iron for iridium? Compared to naquadah everything is going to be easier to get really as it is basically the hardest ore to get in the game and all non-ore methods are high tier or take ages to get.

**Comment by DarknessShadow** [comment]
I do not think we should keep the "intended costs" but make it more expensive because this should be a "Hardcore Modpack" and if we kept the indended costs and didn't change anything in this mod the running cost for a Stargate would only be 84eu/t and the recipes wouldn't have any EV gregtech parts.
If you are already in EV-Age then iron is basicly free.

I think we have to change it to make it more expensive.

**Comment by Xavion3** [comment]
If you're in the EV age the iridium you suggested is basically free, I'm saying why bother changing it when it's not really a cost anyway as that's the naquadah. The iron is there so it has an excuse of creating stargate compatible materials as naquadah is not really any use as a building material, if you're really so desperate to increase it for no reason just make it use steel or something but there's not really any point as basically every material in the game is significantly more easy to get then naquadah by the time you're actually considering stargates and the few that aren't are near entirely stupidly expensive and radioactive so make zero sense anyway.

**Comment by DarknessShadow** [comment]
So the iridium in the recipe i want is to cheap?
Then change it to osmium.
I have 600 naquada but only 150 osmium.

**Comment by Xavion3** [comment]
That was totally not my point, my point was that it's about the naquadah, I mean if you're that desperate to make everything expensive for no reason other then it not seeming expensive why don't we just make iridium wires required for LV machinery, or how about all uses of hammers are replaced by dragon eggs? Also cauldrons should be made out of iridium plates too because we don't want people skipping through thaumcraft do we, that'll make people really pay for everything won't it?

If you have naquadah and you can supply the power (which is getting increased) why shouldn't you be able to make stargates? I mean there are already a variety of solutions to making item and fluid transportation easier, making this so stupidly expensive just for the sake of being expensive will just make it so there is zero point to using compared to alternatives like the teleporter for player transport.

**Comment by AiwendilCiunio** [comment]
I also think increasing the stargate cost is pointless. It's sufficiently expensive now for what it does. Making it more expensive (material- and energy-wise) will just stop people from even bothering.

**Comment by JasonMcRay** [comment]
As @Xavion3 and @AiwendilCiunio said. There is no point on making it more expensive. The expense in here will be with the EU usage.
