### ISSUE TITLE
Missing cobblestone macerator recipe

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#288]
The cobblestone -> sand macerator recipe is gone. I'm not sure if that was @Blood-Asp or us. The pulverizer recipe is still there, but for some reason it's not working on macerators (it's a 2 EU/t recipe, so it should work fine in any macerator, steam or not).

**Comment by AiwendilCiunio** [comment]
Well I just tried and its working fine in MV macerator.

**Comment by Timeslice42** [comment]
Try it in steam and LV. I know it doesn't work in steam.

**Comment by JasonMcRay** [comment]
I was not messing with it. Or at least not in between the pack update. Some script might have been unlocked with IC2 update, since there is a mention about Macerator Recipe "fix" (http://jenkins.ic2.player.to/job/IC2_experimental/743/changes). Not sure if it is related.

In any case if it works in MV mac, and it still uses 2EU/t it should be processable in Steam/LV mac as well.

**Comment by JasonMcRay** [comment]
Tested in DEV:
Cobble -> Sand
Works in LV
Works in MV and higher
Doesnt work in Steam versions.

I summon @Blood-Asp before I will report it in his issue tracker

**Comment by JasonMcRay** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/issues/90
