### ISSUE TITLE
Aerial Interface

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#302]
I think you should reenable the Aerial Interface but change the recipe to something CRAZY EXPENSIVE (eg. neutronium) because there is no config to increase the energy cost of it and when you have fusion tier3 you practically have infinite energy and it doesnt matter anymore.

**Comment by Xavion3** [comment]
It's meant to be useful before T3 fusion though as by the time you hit that it's basically long since useless, really any of the fusion reactor dependent materials it's basically useless a fairly long time before you reach that point. Remember that it's only notable use is when you're away from your base either mining or exploring, having it not available until long after there is zero need for that is pointless, much simpler to just keep it fairly mid game as it would be with the default recipes.

Unless you have a reason why it should cost stupidly large amounts? Note that not being able to cost stupidly large amounts of energy isn't a reason as that's just a different increased cost.

**Comment by DarknessShadow** [comment]
So charging your armor while you are wearing it anywhere in the world is useless once you have t3 fusion?
The energy cost to run it is really low so you have a almost free item teleport system (logistics pipe inventory system connector).
Accessing ALL of your items from anywhere in the world is uselss becomes useless ? (remote orderer)

I always thought this should be a "GregTech balanced hard-mode modpack" and keeping default recipes or a (almost) no running cost infinite range item teleporter is hardly "hard-mode".

**Comment by Xavion3** [comment]
I'm going with yes to both cases, for the first why are you changing armour? By the time you hit T3 fusion you've easily been able to make your ultimate armour whether it's gravisuite, fortress, or dark steel you should have zero reason to change it while thousands of blocks from your base. And yes accessing your items is basically useless, what are you actually doing thousands of blocks from your base that you need tons of items for?

If you really care make it use something relevant like a wireless access point or a singularity, they're basically what it's competing with after all.

**Comment by Xavion3** [comment]
It also isn't really useful as an item teleporter compared to things like magic mirrors or transceivers, really the transciever can basically do this anyway you just have to stop and place it each time. If you're comparing it to things like actual item teleportation it comes out badly even now, your change would make it worse then laughable as it would require effectively unlimited resources to reach that point and billions of EU investment to make making it near totally compared to its many competitors.

**Comment by JasonMcRay** [comment]
It will probably be somewhat around the time you will be able to make other teleportation methods, like Dim Transceiver
