### ISSUE TITLE
Vacuum Hopper

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#313]
The vacuum hopper is disabled.
Please enable it.

**Comment by JasonMcRay** [comment]
Why? You can use Vacuum Chest, Killer Joe or Brain in a Jar.

**Comment by DarknessShadow** [comment]
Because its kinda strange that the only way to collect xp from the ground is with thaumcraft and if you dont have thaumcraft and want a mobfarm (and dont care about xp) the xp will just be on the ground and eventually lag the server.

**Comment by JasonMcRay** [comment]
Killler Joe also atracts XP to itself, and combined with for example Air Crate from PneumaticCraft you can funnel the xp blobs to it.

**Comment by DarknessShadow** [comment]
So we have to use Killer Joe for mobfarms?

**Comment by JasonMcRay** [comment]
You can jsut use Killer Joe for collecting the XP and have the mob farm for example vanilla drop style

**Comment by DarknessShadow** [comment]
But why do you want to limit our xp collectiong to Brain in the Jar and Killer Joe?

**Comment by JasonMcRay** [comment]
You can use Brain, Killer Joe, XP Drains, OpenComputer Robots, why to add another one

**Comment by DarknessShadow** [comment]
Last time I tried XP drains dont collect xp.
Vacuum Hoppers are very good for mobfarms because they can collect items AND xp and work with every killing method.

**Comment by JasonMcRay** [comment]
I just right now tested drains to make sure they work.

So instead of 1 block to collect everything you will have two... Not a big deal

**Comment by groveham** [comment]
XP drains only collect XP from a player when they are stood on as long as they are connected to openblocks tanks :)

**Comment by JasonMcRay** [comment]
No... XP Drains will collect XP blobs if they will land on them... I just right now tested it in v3.1.5

**Comment by lafflam** [comment]
@JasonMcRay, I *think* you'll like this. I began researching data for this post with the hope of providing justification for adding the vacuum hopper back into the game. I *think* I have accomplished that goal... just not the way I had hoped :-)

Why do I think it is important to include the Vacuum Hopper in the modpack?

The simple answer is that I like options. I think it is boring when everyone uses the same golem tree farm. It works early game, but there is little reason to explore other mods later. I want my farm to be different. I want to be able to design a system that nobody else uses on the server. And when items are simply removed from mods, I lose options. The Vacuum Hopper is able to do things that other blocks cannot and/or it does things differently which leads to interesting design ideas.

It could be used in place of a golem gatherer for a tree farm, so it would need to be AT LEAST that expensive. It could be used in place of an XP drain, so it needs to be AT LEAST that expensive too. When combined with Golden or Diamond Spikes, it certainly gets close to the functionality of a Killer Joe, so it needs to be somewhat expensive or else players will never explore the Killer Joe. 

And then there is the Vacuum Chest. That one hurt. But first, some pros and cons of blocks compared to the Vacuum Hopper...

_XP Drain_
Pros:
* Collects XP
* Useful to stand on and store XP from player
* Relatively cheap

Cons:
* Does NOT generate XP (still need something to do the killing)
* Does NOT generate any mob drops
* Does NOT collect any items

Cost:
* 9 iron bars... which is free if you find a stronghold like i did, otherwise 12 iron ingots and some tools
* 5 glass panes
* 4 obsidian (implies tier 3 pick, but players can find diamonds or compress them from coal, which is a little time consuming, but easy enough to get in bronze age)

_Gold Spike_
Pros:
* Generates XP
* Generates mob drops

Cons:
* Does NOT collect XP (still need something to collect it)
* Does NOT collect any items
* A little expensive in gold, but not outrageous

Cost:
33 gold, some tools, an enchanting table, books and wood

_Diamond Spike_
* Basically as Gold spike
* Requires 15 additional diamonds
* Generates rare mob drops too

_Killer Joe_
Pros:
* Generates XP
* Collects XP
* Generates mob drops, including rare mob drops

Cons:
* Does NOT collect items
* Requires Nutrient Distillation
* Needs much more infrastructure to acquire

Cost:
* 3 dark steel... which is free if you find some, otherwise implies at least MV
* 5 fused quartz... which is LV and a trip to the nether
* 1 frank'n'zombie... which is LV and the following: Soul Binder, Slice'n'Splice, zombie soul vial, 2 x Gold, 2 Soulsnad, 2 x Silicon plates (MV), zombie head and redstone)

Up to this point I was thinking the Vacuum Hopper could fit in between somewhere... maybe cheaper than the Killer Joe, but more expensive than the XP drain. That is until I compared it to the Vacuum Chest.

_Vacuum Chest_
Pros:
* Collects all items (not just mob farms, could be used in lieu of golem gatherer, for example)

Cons:
* Does NOT generate items (still need something to do the mob killing)
* Does NOT generate XP (still need something to do the mob killing)
* Does NOT collect XP

Cost:
* 7 iron ingots
* 1 chest
* 1 pulsating crystal (LV, diamond dust, molten pulsating iron which is MV, I think)

It seems the functionality of the Vacuum Hopper is closest to the Vacuum Chest (minus the storage, but able to collect XP).

_Vacuum Hopper_
Pros:
* Collects XP
* Collects all items (not just from mob farms, so could be used in lieu of golem gatherer)

Cons:
* Does NOT generate XP (still need something to do the killing)
* Does NOT generate items (still need something to do the killing)

Cost (default Openblocks recipe):
* Hopper (10 iron ingots, tools and a chest)
* Ender Pearl
* Obsidian

The Openblocks recipes are notoriously cheap. So in order to Gregify (or should that be Malify) a recipe for a Vacuum Hopper, here is a suggested recipe: 

Suggested Cost:
* Hopper (10 iron ingots, tools and a chest)
* Pulsating crystal

This makes it about as expensive as a Vacuum Chest, but with completely different design implications. Sadly, this is way more expensive than I had hoped in the beginning. However, I'd rather give players the option of using a Vacuum Hopper if they can come up with a design that fits it. Maybe it's a mob farm, maybe it's an overpriced egg collector. Who knows?

Just my $0.02. :-)

**Comment by pyure** [comment]
I still haven't heard why the vacuum hopper is a bad idea.  I've heard lots of reasons why it could be added.  What's the downside?

**Comment by lafflam** [comment]
I do not speak on behalf of Jason, but sometimes Openblocks recipes can be very cheap compared to other items in the game with similar functionality. This is supposed to be a hard pack with expensive recipes.

In this case, a standard Vacuum Hopper and Vanilla chest could do everything a Vacuum Chest can do without any tech infrastructure to build it, so who would bother with the Vacuum Chest? Easier to just eliminate the cheap duplicate recipe.

 The problem is that the Vacuum Hopper offers singularly unique build ideas compared to anything else. So I think it just came down to carefully analyzing its abilities and cost to manufacture, and then recommending a recipe that brought in line with other items in the pack.

Looking forward to analyzing more items to see if the can be reintroduced in similar appropriately-expensive  fashion :-)

($0.02)
