### ISSUE TITLE
Fluid / Item Conduits

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#315]
I think the fluid and item conduits are way too cheap compared to other transport methods especially the gregtech item / fluid pipes when we consider that the conduits don't need conveyors / pumps / Item Filters attached to work.
Thats why we should change the recipe to include gregtech pipes which would also integrate the conduits better into the gregtech tier system.
The recipes for them should look something like this:

1x Fluid Conduit:
---------------------- Conduit Binder
Nether Quartz --- (Small) Bronze Fluid Pipe --- Nether Quartz
---------------------- Conduit Binder

1x Pressurized Fluid Conduit:
Conduit Binder --- Vibrant Alloy Nugget ------ Conduit Binder
Fused Quartz ---- (Small) Steel Fluid Pipe --- Fused Quartz
Conduit Binder --- Vibrant Alloy Nugget ------ Conduit Binder

1x Ender Fluid Conduit:
Conduit Binder --- Enderium Nugget --------------------- Conduit Binder
Fused Quartz ---- (Small) Tungstensteel Fluid Pipe --- Fused Quartz
Conduit Binder --- Enderium Nugget --------------------- Conduit Binder

1x Item Conduit:
------------------------------- Conduit Binder
Pulsating Iron Nugget --- (Small) Electrum Item Pipe --- Pulsating Iron Nugget
------------------------------- Conduit Binder

**Comment by AiwendilCiunio** [comment]
These are recipes for ONE conduit? I think you are looking at the recipes from a perspective of a player who has everything, not a player who is early/mid game. I think conduits shouldn't be a lategame solution, this mod is here because conduits are very useful and shouldn't be restricted to lategame.

I like the idea of including gt pipes in the recipes, but in my opinion it should either include small pipes instead of normal ones, or either craft 6 conduits instead of 1.

**Comment by DarknessShadow** [comment]
Crafting 6 conduits instead of 1 from 1 single gt pipe is not good. Why should the conduits that are far superior to the gregtech pipes be 6 times cheaper?

Yes we could change it to have small pipes instead of normal ones.

But 2x Conduit Binder + 2x Nether Quartz + 1x (Small) Bronze Fluid Pipe is an early game recipe.

**Comment by TedKnudsen** [comment]
Nice idea Darkness, although I doubt it will do anything to encourage people to try something besides eIO.  

Aiwen, getting 6 pipes from a single GT pipe would probably just defeat the purpose.  Probably.  Is anyone not-lazy enough to draw up a chart of all the pipes involved, their proposed costs and their estimated worths?

**Comment by Blood-Asp** [comment]
I personally see the recipes as fair. But making things more expensive mid game after everyone got used to the cheap price will end with outrages. 
So, that these changes have even a little chance to get accepted, they must be not this extreme.
How about making the conduit binder recipe similliar to the concrete production? With mixer and fluid solidifier? So the harder recipes are split in steps?

**Comment by Blood-Asp** [comment]
Other ideas: Rise the tiers, make less usefull(lower fluid transfer in configs and remove speedupgrades for item comduits.)

**Comment by DarknessShadow** [comment]
@TedKnudsen
I think when the conduits are more expensive than the gregtech pipes some people will finally use them because right now they are so much more expensive that its totally ignored by most people.

@Blood-Asp
I like the idea of making Stone Dust actually useful :)
But the Fluid Conduit should then need something else in the recipe so we are still able to craft it in Bronze Age.
I didn't know you could change extraction rates on the conduits but with that in mind we could change it to that of the gregtech pumps.
Fluid Conduit as fast as LV Pump 32mb/t (right now its 50mb/t extraction)
Pressurized Fluid Conduit as fast as MV Pump 128mb/t (right now its 100mb/t extraction)
Ender Fluid Conduit as fast as HV Pump 512mb/t (right now its 200mb/t extraction)

Yes making them so expensive mid game is probably problematic for many people so we should use the small pipes in the recipes instead of normal ones.

I do NOT like the idea of removing speed upgrades but I would be totally fine with making them more expensive.

**Comment by Xavion3** [comment]
So my thoughts on them are that boosting costs could be good, but keeping them similar to the current recipes would work best. So I'd suggest just modifying the current recipes to replace the edge two fused quartz with two normal pipes of bronze/steel/tungstensteel replacing them, the recipes would still give 6 conduits from that though. I'd also say increase the EU/t for Vibrant Alloy so it moves up to LV tier from steam tier, it's only used for a few items and only energy and fluid conduits didn't already need at least LV tier so nothing is changed except boosting them to LV tier. The reason for normal pipes with 6 output is because that's the same resource cost as 6 small pipes and those tiers are closest to the conduits in transfer rate for small pipes, +25% speed for the lower two tiers for conduits over pipes to be precise. Lowering it so they have the same output rate as input rate could be good as well.

As for the item conduit, it's actually really slow compared to GT pipes but unlike them doesn't need an addon to extract items. Even with 15 speed upgrades it only seems to hit 2 stacks a second, consequently I'd say that it's current recipe is probably fine, the autoextract feature for all conduits is only useful when considering things which don't possess auto-output remember and that's pretty much just tanks and chests as all ender io and GT machines at least possess that functionality.

So yeah, in summary the autoextract feature isn't actually that useful and they do cost more so just nerf the fluid conduits by including normal pipes instead of glass and making max IO rate equal to extract rate.

**Comment by pyure** [comment]
I think most people hate GT infrastructure no matter what you do with the costs (and despite the fact that GT item pipes are actually really good)

If the hitboxes could be magically fixed, or they could combine liquids/items in a single block a la eIO, people would show some interest, but eIO is just so relatively OP that the recipe costs we're talking about are going to have to be really aggressive in order to make people consider GT.

I'm liking all the notions above, fwiw.  I'll be happy with whichever route we go.  Paragraphs above are just me thinking out loud.

**Comment by DarknessShadow** [comment]
@Xavion3 
I thought the recipes I suggested are already very similar to the original recipes ... ?
I don't like the idea of taking the Fused Quartz (basicly 4x Nether Quartz + 1x Glass Dust) completly out of the recipe and I don't like the 2 pipes -> 6 conduits but maybe thats just my personal preference to have 1:1 "upgrade" recipes so better use small pipes in the recipes.
If we change the recipe of the Conduit Binder to require Wet Concrete then we don't need to move the Vibrant Alloy to LV.
You have to consider that you don't actually extract a ton of the same item but lots of different items with small stack sizes which means Item Conduits are better for it.

**Comment by Xavion3** [comment]
If you change conduit binder to LV it also means you have to use GT pipes for all of steam basically and that normal fluid conduits are useless as people will have no reason not to skip to pressurized, BC pipes are fairly slow and how well can they even deal with auto-output?

Yours were similar to the original recipes, just considerably more expensive, +33% or more in everything but pipes. Although my suggestions do remove the requirement for fused quartz in the two higher tier recipes that can be countered if people really want, I'm not sure why though as what the changes would do would make the pipes the defining feature of fluid conduits, not the quartz.

Also item conduits only extract twice a second as far as I can tell so they're really not that much better, 2x speed but 16x less per extraction so they're going to be inferior in pretty much every case. It's really not much of a concern here.

**Comment by DarknessShadow** [comment]
1) When I first wrote about the changed conduit binder recipe I mentioned that we need to change the recipe of the Fluid Conduit so you can make it in Bronze Age (with glass dust instead of conduit binder or something)

2) Whats so bad about 33% more expensive? ;D

3) I basicly want to keep the Fused Quartz so the recipe is still somewhat similar to the original.

**Comment by Xavion3** [comment]
1) Missed that, it would be important though.

2) +33% *or more*, you use +33% vibrant alloy and enderium, +500% quartz, and +300% conduit binders. It's slightly different for the lower two in +100% conduit binder, +300% pulsating iron, and surprisingly no extra quartz for basic fluid conduits. That's before adding in the cost of the GT pipes of course which ratchet things up by a plate of whatever in each.

3) It would still be, mine is basically just changing only the fused quartz but other then that it's identical to what is currently there, the originals are basically the same as current except a tier lower in cost.

**Comment by DarknessShadow** [comment]
Now they aren't that similar to the originals but what do you guys think about it?

2x Fluid Conduit:
Glass Dust ------------------- Nether Quartz --- Glass Dust
Small Bronze Fluid Pipe --- Nether Quartz --- Small Bronze Fluid Pipe
Glass Dust ------------------- Nether Quartz --- Glass Dust

2x Pressurized Fluid Conduit:
Conduit Binder ------------ Vibrant Alloy Nugget --- Conduit Binder
Small Steel Fluid Pipe --- Fused Quartz ----------- Small Steel Fluid Pipe
Conduit Binder ------------ Vibrant Alloy Nugget --- Conduit Binder

2x Ender Fluid Conduit:
Conduit Binder ----------------------- Enderium Nugget --- Conduit Binder
Small Tungstensteel Fluid Pipe --- Fused Quartz ------- Small Tungstensteel Fluid Pipe
Conduit Binder ----------------------- Enderium Nugget --- Conduit Binder

2x Item Conduit:
----------------------------------- Conduit Binder
Small Electrum Item Pipe --- Pulsating Iron Nugget --- Small Electrum Item Pipe
----------------------------------- Conduit Binder

1x Conduit Binder in the Fluid Solidifier:
Mold (Ball) + 36mb Wet Concrete = 1x Conduit Binder

**Comment by AiwendilCiunio** [comment]
I quite like it actually.

**Comment by pyure** [comment]
Yeah, works fine for me.

Btw, people frequently overlook wooden GT pipes in the early game. They're absolutely terrible for throughput and cannot handle steam or gases, but are are good enough for all your water-transporting needs at that point.  And they're dirt cheap and easy to make.

**Comment by Timeslice42** [comment]
Ingots are 144mb because 9 * 16  = 144. 16 is nice power of two; it's not our fault ingots have nine nuggets...

This whole conversation brings me back around to my old "get rid of eI/O conduits" thought experiment. Sometimes I miss the large, convoluted, and fun-to-watch builds that you get when you use Logistic Pipes and BC pipes. However between AE2 and eI/O conduits there really isn't much reason to use LP.

**Comment by pyure** [comment]
I could get by without my eIO infrastructure bits if I had to, but I kinda chalk it up under "shit that would cause more anarchy in the streets than its really worth."

**Comment by JasonMcRay** [comment]
i like that @DarknessShadow although one tiny issue... there are no small electrum item pipes :)

**Comment by DarknessShadow** [comment]
@JasonMcRay Hm the idea with small pipes came later and then I didnt check if they actually exist ^^
(strange item pipes are only normal, large and huge)

Btw i forgot to add this on my lastest post were I summarized it all
I think it would be good if we make the extraction rates equal to the gregtech pumps.

Fluid Conduit as fast as LV Pump 640L/sec = 32mb/t (right now its 50mb/t extraction)
Pressurized Fluid Conduit as fast as MV Pump 2560L/sec = 128mb/t (right now its 100mb/t extraction)
Ender Fluid Conduit as fast as HV Pump 10240L/sec = 512mb/t (right now its 200mb/t extraction)

**Comment by pyure** [comment]
I didn't think the point here was to make the eIO pipes any better than they already are (which is the case in some ways above)

**Comment by Timeslice42** [comment]
I don't know about making them equal to the pumps, but the idea of making them at least as good as the pipes they are made from is worth exploring.

**Comment by JasonMcRay** [comment]
I think its worth to balance it and made them bit "faster" since we nerfed recipes. Either I will change them as proposed by DS to be equal to pump modules, or to be equal to pipes they are made of (dont know the values from to of my head)

**Comment by DarknessShadow** [comment]
Small Bronze Fluid Pipe = 800L/sec = 40mb/t
Small Steel Fluid Pipe = 1600L/sec = 80mb/t
Small Tungstensteel Fluid Pipe = 4000L/sec = 200mb/t

**Comment by JasonMcRay** [comment]
OK.... Making them to match the pumps is bit too much. So I am going with my own "gut feels"
50,120,300
