### ISSUE TITLE
Red Dye

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#340]
The flowers from extrabiomxl dont have a extractor recipe to give 2 dyes instead of 1.
Please add them:
Gloriosa
Red Rover
Poppy
Red Gerbera
Red Amaryllis

edit: actually the problem is will all flowers(all colors) from extrabiomexl

**Comment by JasonMcRay** [comment]
@Blood-Asp would it be possible to add it natively to GT? If so I can open ticket on your git.

**Comment by Blood-Asp** [comment]
I was thinking of readding the spraycans anyways, so i can do this colorstuff also... Do the flowers have oredict? Are there other colors of flowers not beeing able to be processed?

**Comment by JasonMcRay** [comment]
@Blood-Asp EXBL flowers are not in any oredict.

Here is list of them and their produce, generated via Minetweaker, because I cant be bothered to write it manually :p:
Output, input

<minecraft:dye:2>, [<ExtrabiomesXL:waterplant1>]);
<minecraft:dye:1>, [<ExtrabiomesXL:vines>]);
<minecraft:dye:11>, [<ExtrabiomesXL:flower3:11>]);
<minecraft:dye:5>, [<ExtrabiomesXL:flower3:10>]);
<minecraft:dye:14>, [<ExtrabiomesXL:flower3:9>]);
<minecraft:dye:14>, [<ExtrabiomesXL:flower3:8>]);
<minecraft:dye:1>, [<ExtrabiomesXL:flower3:7>]);
<minecraft:dye:1>, [<ExtrabiomesXL:flower3:6>]);
<minecraft:dye:11>, [<ExtrabiomesXL:flower3:5>]);
<minecraft:dye:9>, [<ExtrabiomesXL:flower3>]);
<minecraft:dye:11>, [<ExtrabiomesXL:flower3:4>]);
<minecraft:dye:13>, [<ExtrabiomesXL:flower3:3>]);
<minecraft:dye:5>, [<ExtrabiomesXL:flower1:3>]);
<minecraft:dye:5>, [<ExtrabiomesXL:flower3:2>]);
<minecraft:dye:12>, [<ExtrabiomesXL:flower1:1>]);
<minecraft:dye:11>, [<ExtrabiomesXL:flower2:15>]);
<minecraft:dye:1>, [<ExtrabiomesXL:flower2:14>]);
<minecraft:dye:9>, [<ExtrabiomesXL:flower2:13>]);
<minecraft:dye:14>, [<ExtrabiomesXL:flower2:12>]);
<minecraft:dye:7>, [<ExtrabiomesXL:flower2:11>]);
<minecraft:dye:7>, [<ExtrabiomesXL:flower1:7>]);
<minecraft:dye:11>, [<ExtrabiomesXL:flower1:2>]);
<minecraft:dye:6>, [<ExtrabiomesXL:flower3:13>]);
<minecraft:dye:12>, [<ExtrabiomesXL:flower2:6>]);
<minecraft:dye:10>, [<ExtrabiomesXL:flower2:5>]);
<minecraft:dye:1>, [<ExtrabiomesXL:flower2:2>]);
<minecraft:dye:9>, [<ExtrabiomesXL:flower2:1>]);
<minecraft:dye:13>, [<ExtrabiomesXL:flower2>]);

**Comment by Blood-Asp** [comment]
putting that list into GT5 as extraction recipes should be easy. But please open a issue at GT5 issue tracker so do not forget about it until the next release.

**Comment by JasonMcRay** [comment]
done
