### ISSUE TITLE
Strange Ore Generation

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#363]
Dlur100 showed me something strange on the server, an ore vein consisting of:

Redstone Droppers (vanilla)
Redstone Compatators (vanilla)
Acacia Sapplings (vanilla)
Fences (Vanilla)
Crystal Growth Accelerators (AE2)

I have screenshots to show the issue, I've never seen anything like it. From the co-ords I can't say if these chunks were created recently but no one else has ever mentioned anything like this. It's not a visual bug because I broke the blocks and picked up the drops. 
Not sure what to make of this and I'm not sure how re-producable it is or how common the issue is. 
![2015-09-24_18 35 45](https://cloud.githubusercontent.com/assets/1354486/10081281/0e59146c-62ec-11e5-94cf-98775857b517.png)
![2015-09-24_18 35 49](https://cloud.githubusercontent.com/assets/1354486/10081280/0e57352a-62ec-11e5-9b7b-ee3e213a8273.png)
![2015-09-24_18 35 58](https://cloud.githubusercontent.com/assets/1354486/10081282/0e5a9d64-62ec-11e5-8d56-1400c98c12cb.png)
![2015-09-24_18 36 20](https://cloud.githubusercontent.com/assets/1354486/10081279/0e56ffe2-62ec-11e5-9259-94f2955b094a.png)

**Comment by JasonMcRay** [comment]
From the layout I guess it was supposed to be GT vein? I doubt it is newly generated chunk. @Blood-Asp do you have any idea, what could cause this in GT?

**Comment by Blood-Asp** [comment]
The only thing i can think about when seeing this is a corrupted savegame... Did maybe all old oreveins change, or only a few?

**Comment by groveham** [comment]
Well only this one as far as I know, no one else has said they've found something like this so far, but then again, this map has been around since the start of v3.0.0

**Comment by JasonMcRay** [comment]
Well what you could try out is to reset the chunk (delete the chunk and let it regenerate). It should then generate normal ore, what is supposed to be in there. Also since as you said the world has been there since the start of v3, these regenerated chunks might look wierd or out of place.

There is nothing else anyone can do about it.

I guess this is really rare issue, so... I guess we can ignore it for now... If you will find something similiar in freshly generated chunks, then we might have a problem.
