### ISSUE TITLE
Review whether Blue Power is still a good fit for the pack

### ISSUE THREAD

**Issue by Dlur100** [JasonMcRay/InfiTech-1.7#408]
Blue Power seems to be abandonded by the mod dev.  There are incredibly laggy items in the pack, like the Auto Project Table.  Also there's a very easy to exploit duplication bug that works for any item: https://github.com/Qmunity/BluePower/issues/419

**Comment by lafflam** [comment]
I use Blue Power a lot, and I agree the Auto Project Table can be laggy (even when it is not doing anything). But I have NOT found any other Blue Power machine that causes lag. Perhaps we could just  remove the recipe for the BP Auto Project Table from the server.

That said, hopefully the Blue Power team is still active enough to fix that item duplication glitch. Tested on the server and it does work, sadly. Players could easily duplicate ANY item that can go in a barrel. JABBA dev points to BP not handling zero size stacks properly. :-(

**Comment by JasonMcRay** [comment]
In short.. I cant just like that remove BP. It will cause pain to those players using BP gates in big amounts. @amadornes said (https://github.com/Qmunity/BluePower/issues/415#issuecomment-152818129) that BP is going through big rewrite. Disabling items from crafting is fine, but removing mod because of just some lag and dupe is not a reason to do so, at least not yet. If it causing issues, than dont use those features.

**Comment by Dlur100** [comment]
Fair enough Jason.  The dupe bug with transposer is super easy to use and is probably worse than the ExtraCells dupe bugs because you can duplicate any item that can be placed in a JABBA, including things like europium plates or even things that can't be replicated with UUM.  

I wonder if it would be possible for @amadornes to fix this one bug despite the rewrite as it could be quite game breaking?

**Comment by amadornes** [comment]
I don't really know how easy it'd be for me to fix it, since I have no idea how any of the tube code works (that's @MineMaarten's part of the mod) but I could look into it. I was going to go over it in this update anyways to try to understand how it works and see if I can fix a couple other issues, but I may as well just learn about it now :P
The only thing I can think of that could cause any kind of problems would be merging the two branches later on (since the one I'm working on right now is going to bring *HUGE* changes. I don't know how happy git would be with it... But I could always try :P

**Comment by lafflam** [comment]
Would it be simple enough program the Transposer so that it does not respond to a redstone pulse?

That way 1) the recipe for the Transposer remains the same, 2) the Transpose can still collect items dropped nearby like normal, 3) the Transposer could still be used in the recipe to make the Relay, and 4) the dupe bug should stop working because the Transposer stops pulling items out of inventories.

This would only be a temporary fix until the rewrite is launched and the Transposer is fixed properly.

Is that possible?

**Comment by JasonMcRay** [comment]
Since I gave my stand on this matter: If BP is going to stay in modpack (yes it will stay). Closing this.
