### ISSUE TITLE
Can't dismount Titanium pipe with Iron Wrench.

### ISSUE THREAD

**Issue by antkatcin** [JasonMcRay/InfiTech-1.7#430]
Looks like i can't dismount Titanium pipe with Iron Wrench (works well on Bronze ones). Is that intentional?

![2015-11-22_18 25 53](https://cloud.githubusercontent.com/assets/3091327/11323766/af93c4de-9146-11e5-8266-3c685d0651f2.png)

**Comment by JasonMcRay** [comment]
Is the issue only with Titanium pipes? Can you try higher tier pipe if you will be able to break it? Will better wrench works? For me it seems intentional (@Blood-Asp confirmation) that low tier wrenches will not work on higher tier pipes? (Same as for example you cant mine iron with wooden pickaxe)

**Comment by Blood-Asp** [comment]
mining level also counts for tools, iron is a tier 2 tool, titanium a tier 3 material. So everything working as intended.
