### ISSUE TITLE
Cutting Machine no longer working on Forestry logs

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#442]
It used to be that you could put forestry wood into the cutting machine and get wood planks and wood pulp. That is no longer working, probably due to the derp with NBT data on forestry logs.

**Comment by JasonMcRay** [comment]
It is fixed in latest forestry, to which we cant update yet, because of GT5.08 needs again to update to new API.

**Comment by Timeslice42** [comment]
I imagine @BloodAsp is going to skip that in favor of doing it in 5.09?

**Comment by Blood-Asp** [comment]
Fixed in latest unstable forestry, or did the fix allready get pushed to forestrys curse release? In case it is allready out of unstable, i will take care of GT5.08 this weekend. The way forestry broke the log registering before was just too much work for me to care. Also did not fix it in the GT 5.09 versions.

**Comment by JasonMcRay** [comment]
Yes. 4.2 is released on curse. It contains the change with logs to use meta instead of nbt.

**Comment by JasonMcRay** [comment]
fixed in 38ea05d7a1ba663faec8ece1a4c3bd12db9c4d34
