### ISSUE TITLE
[3.2] - Thaumonomicon is not returned making copper caps in Arcane Worktable

### ISSUE THREAD

**Issue by Dlur100** [JasonMcRay/InfiTech-1.7#516]
When attempting to make copper wand caps in an arcane workbench the thaumonomicon is used up instead of being returned.

**Comment by Xavion3** [comment]
The relevant line of script is [here](https://github.com/JasonMcRay/InfiTech-1.7/blob/master/scripts/thaumcraft.zs#L1073) and seems to be working fine in most things. Out of my quick tests it works in the crafting terminal, worktable, fancy workbench, crafting table, production table, crafting table cover and translocator crafting grid and doesn't work only in the arcane workbench or XACT crafter or craftpad. Using giveBack or transformReplace instead of reuse doesn't help those two give the thaumonomicon back.

Unfortunately thaumcraft development for 1.7.10 ended ages ago so I don't think anything can be done about this, just use basically anything except for the arcane worktable. Luckily you need wand caps before you can get the table so it shouldn't crop up much.

**Comment by Dlur100** [comment]
Xavion, within the thaumonomicon I think it's possible to display crafting recipes a couple of ways: on a vanilla crafting table, arcane workbench, or other thaumcraft methods (infusion altar for example).

I'd look in the thaumonomicon to see how the recipe for copper wand caps is displayed, but I can't (because the book's gone :P)  but I'm pretty sure the recipe displays as arcane workbench, not vanilla craft.  If it's possible to change that in the code, that'd be good and help avoid this bug.

Obviously nobody is going to create their first copper wand on an arcane workbench, but I also don't know anyone that uses thaumcraft that only ever crafts 1 wand.  For subsequent wands it's not improbable that an arcane workbench might be used, and POOF!

**Comment by Xavion3** [comment]
Only the copper wand caps require the thaumonomicon, it's not required for the silver, thaumium, or void caps, in fact you need an arcane worktable and vis to get those.

Also no it doesn't, it displays as a workbench recipe because it is a workbench recipe, you have to actually set it as an arcane workbench recipe for it to display as one. Took an image for reference, shows the pages on copper wand caps.
<img width="604" alt="screen shot 2016-03-22 at 2 48 00 am" src="https://cloud.githubusercontent.com/assets/3487253/13924504/bc3c64c0-efd8-11e5-9ecd-4583a629817a.png">

So yeah, this is an issue but fairly minor, the only times it will crop up is in the XACT crafter or if you've somehow got an arcane workbench without having a wand and are using that. I'll add a note in the next version of the quests about it though.

**Comment by JasonMcRay** [comment]
Its happening because TC and XACT recipe handler for this crafting method doesnt accept IIngredient. So either we will need to find another solution for the progression, or just go with it.

**Comment by JasonMcRay** [comment]
Since TC is no longer maintained for 1.7 and XACT is also moving to 1.9. Closing this. I will try to fix it at least in XACT in my fork, maybe... if I will learn how to do that.... or if anyone else will want
