### ISSUE TITLE
3.2 Dupe bugs

### ISSUE THREAD

**Issue by Corax90** [JasonMcRay/InfiTech-1.7#546]
While playing on the official server, the bibliocraft armor stand duped my armor after switching it with shift+r-click (redstone signal was applied on the armor stand). Then my silver capped greatwood wand got duped too but i dont know the cause (maybe something related with the arcane worktable?)

**Comment by Timeslice42** [comment]
Are they for sure duped, or did they disappear after you reconnected to the server?

**Comment by Corax90** [comment]
duped for sure, i still have them

**Comment by Timeslice42** [comment]
What was the armor that you were wearing, and what was on the stand?

**Comment by Corax90** [comment]
I was wearing bewitched robes, bewitched leggings and thaumaturge's boots. on the stand there was a steel chest plate if i remeber well. The chest plate is gone, the thaumcraft armor got duped.

**Comment by JasonMcRay** [comment]
The armor dupe happend probably because of lag. I am unable to recreate it. If it is really the case, and its only one time issue... there is not much to be done. If the dupe will happen again, please re-open (or submit a new issue).

As for the wand... as long as you will not provide steps leading to the dupe, not much can be done in here.

**Comment by Timeslice42** [comment]
I've heard of this with armor stands before (in MC 1.6.4, I believe), but I've never had it happen. It might be an SMP/lag only thing.
