### ISSUE TITLE
EV Battery Charger recipe bugged

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#573]
EV Battery Charger recipe is bugged and not craftable, seems it doesnt recognize the lapos or the green data circuit thingy.

**Comment by JasonMcRay** [comment]
Its most likely lapotrons. Since I don't think I was doing something with the Battery Charger recipes gonna summon @Blood-Asp for confirmation and if that is the case of GT bug, will be reposted to GT issue tracker directly afterwards :)

**Comment by Blood-Asp** [comment]
On my side the EV charger recipe seems fine. Used it a few weeks back (GT5.09.19).

**Comment by JasonMcRay** [comment]
@Blood-Asp just tested in pure GT5 instance... It doesnt work. it only works with Lapotrons without Meta. which are impossible to get since crafting fresh one will always give you with meta.

Not working with lapotrons:
![2016-04-02_00 47 20](https://cloud.githubusercontent.com/assets/4236895/14222048/8fa3909a-f86c-11e5-808c-2b5428b8b645.png)

NEI is showing this:
![2016-04-02_00 47 17](https://cloud.githubusercontent.com/assets/4236895/14222059/9f6df88a-f86c-11e5-816d-6da18007cd07.png)
If I will cheat in Lapotrons by /give command to have them without META, the recipe works.

**Comment by yznpku** [comment]
@JasonMcRay You should put that data stick on the grid lol.

**Comment by Timeslice42** [comment]
Yeah, @JasonMcRay the recipe in the first picture you're showing isn't correct anyways. I'm assuming you've also already tried it with the correct recipe?

**Comment by JasonMcRay** [comment]
The recipe accepts both Data Stick and Data Circuits.

**Comment by Blood-Asp** [comment]
For some reason i did not make the lapo oredict... changed that: https://github.com/Blood-Asp/GT5-Unofficial/commit/9e5819e93106ea31cdb724b2b378dc55251ca73f
Wonder why it does not work for you but on kirara there was no issue for me to craft it...

**Comment by JasonMcRay** [comment]
Well maybe they fixed it on Kirara with Minetweaker and did not bothered to
let you know? :)

2016-04-02 16:19 GMT+02:00 Blood-Asp <notifications@github.com>:

**Comment by DarknessShadow** [comment]
So @Blood-Asp fixed it 21 days ago in https://github.com/Blood-Asp/GT5-Unofficial/commit/9e5819e93106ea31cdb724b2b378dc55251ca73f when will we get that in InfiTech2?

**Comment by JasonMcRay** [comment]
When GT is updated to .22
