### ISSUE TITLE
Bees shouldnt produce Dragon-Eggs, instead it could be obtainable through a Quest

### ISSUE THREAD

**Issue by DerEchteLanger** [JasonMcRay/InfiTech-1.7#610]
Due to the magic energy absorber from GT using lots of dragon eggs for energy is very easy, so once you got the bees neccessary its possible to make as much maintainance free energy as wanted. It would not be helpfull to ban the making of dragon-eggs, since there is only one per server and that would be kinda unfair to people who never got the chance to grab it. 
So my suggestion: Make a quest to obtain an egg, which can only be done once per player. It could require the draconic chunks like the crafting recepie...

**Comment by JasonMcRay** [comment]
I dont want to have anything relying on quests. Not everyone is doing quests. Quests are just as walkthrough for new players. But I see your concern. Might add a diferent way, but some testing is needed to ensure no exploits

**Comment by Timeslice42** [comment]
Don't forget that the EV energy absorber takes Mk 1 fusion to make. However it's pretty simple to just disable the draconic bees. If people want more eggs they can kill more dragons.

**Comment by ct-klein** [comment]
Don't you NEED a dragon egg in order to use the temple caller to reset the end to get more dragons or did that mechanic change?

**Comment by JasonMcRay** [comment]
Yes. You need Dragon egg to placed on pedestal in the temple to regenerate the End

**Comment by ct-klein** [comment]
Right, I'm just thinking that people might be less than willing to give up their original dragon egg which is probably being used and which is consumed in the process, in order to have to fight another dragon just to get another egg.  I'd leave it alone especially since some bees (at least used to) require the dragon egg to be in proximity to breed.

**Comment by Xavion3** [comment]
Currently the bees are the only way to get more dragon eggs yes, as while there are two methods of resurrecting the dragon both consume the egg in the process.

**Comment by DerEchteLanger** [comment]
Which is the other method than the temple caller?

**Comment by Xavion3** [comment]
There are bees that can resurrect mobs with their drop, two different kinds which cover a different subset of vanilla mobs. For the enderdragon they need one of their eggs, just throw it near an apiary with them in it and it'll spawn an enderdragon before long, think they're called phantasmal bees or something similar.

**Comment by JasonMcRay** [comment]
Yes, with our current mod set the only options to respawn dragon are Phatasmal bees and temple caller. Both consume the egg.

Only way to get another egg are draconic bees.

Currently I am thinking about these options:
1) Keep draconic bee as it is, but change the recipe for getting the egg from the fragments
2) Remove Draconic Bee and move the fragments to higher tier bee.

Also I am considering adding another way of getting more eggs for those who dont really like bees.

Problem is to make it obtainable, but not too easy, but not impossible

**Comment by Xavion3** [comment]
Holy planks of Sengir surrounded by 8 eggs gives 2 dragon eggs?

**Comment by ct-klein** [comment]
currently the egg is required to make the holy planks and is consumed in the process but that's an easy change, right?

**Comment by DerEchteLanger** [comment]
The most important thing is to limit the nuber of eggs someone can make. No matter how hard you make them, completly free HV (EV after fusion) without any maintainace is op and breaks one of the most important parts of the game, aquiring stable energy...

**Comment by Xavion3** [comment]
Eh, you can do that even without the dragon egg, the generators also take centivis for EU after all which is generated endlessly for free once you've got it. And pretty much any form of power gen can be automated so as to provide power from a closed system given enough effort, from oil to nuclear the main thing of note is that the dragon egg is incredibly easy to setup as a system and while it requires significant initial effort to actually get the ability to setup multiple systems once done so it scales very easily. The ideal solution here would be to make it similarly difficult to get a dragon egg as it is for example to setup an automated oil production and processing line or a uranium transmutation and nuclear reactor system to back it up, not sure how to do so though.

As for the planks, that's why I suggest two yield, although that was more as a random jokey suggestion, make the planks give 2 eggs so you get a net yield of 1 egg.

**Comment by Xavion3** [comment]
Is it possible to make the ender dragon have a chance of dropping a dragon egg? That'd give a way of letting phantasmal bees or the temple caller run at a net gain.

**Comment by DarknessShadow** [comment]
I think the getting another dragon egg should be really expensive AND through a quest so you cannot repeat it for endless dragon egg power.

**Comment by DerEchteLanger** [comment]
Also i just noticed nodes can be overpowered, too. With bees its easy to get a node with like a few hundret cvis, also able to generate lots of maintenace free energy for little price... 
Maybe we could ask Blood-Asp to somehow nerf them, e.g. slowly making the node smaller or requireing a non renewable catalyst item...

**Comment by DerEchteLanger** [comment]
That would also be a great idea for the egg generator, ill make a suggestion at his github.

**Comment by lafflam** [comment]
The only thing I have to add to the discussion so far is that the Temple Caller is disabled on the Official Public Server, and admins should consider disabling it on any server unless players are aware that their builds could be erased in the End (unless I misunderstand how it works).

**Comment by JasonMcRay** [comment]
With the Temple caller.... I am thinking about not caring about it if servers have it disabled, because of the reason you mentioned @lafflam. In the case of disabled Temple Caller server owners should provide different ways of resetting the End. Mainly because of Dragon Essence, which drops only from HEE dragon.

**Comment by yznpku** [comment]
I don't think it's dragon egg's fault.
Instead the material cost of Magic Energy Absorbers should be greatly increased. IMO the EV one should be as expensive as an entire fusion reactor.

**Comment by DarknessShadow** [comment]
>eidt: that goes also for example if servers have Creeper explosions disabled. They they should provide alternatives to obtaining Compressed Ingots

Alumentum?
>I don't think it's dragon egg's fault.
Instead the material cost of Magic Energy Absorbers should be greatly increased. IMO the EV one should be as expensive as an entire fusion reactor.

Making it more expensive is good but not as expensive as a fusion reactor because at that point having 2k eu/t more or less doesnt really matter.

**Comment by Xavion3** [comment]
One option is to make it just not produce 2k EU/t, a cap of 128 EU/t for example would let eggs still be useful while not really being overwhelming most likely. We can set the exact EU/t of eggs once https://github.com/Blood-Asp/GT5-Unofficial/issues/486 is fixed after all, well we can now but the bug means even setting it for 1EU/t would translate to 100EU/t before efficiency percentage.

**Comment by Timeslice42** [comment]
The GT 4 solution for both issues was to spawn wisps while the magic energy absorber was in use. I think adding that back in would be a nice start.

**Comment by DarknessShadow** [comment]
@Timeslice42 But you could then use it as power gen and mobspawner at the same time lol

**Comment by JasonMcRay** [comment]
Closed by https://github.com/JasonMcRay/InfiTech-1.7/commit/76753cb110d4fbac6732e4c721c4f71dc6c83f1f
