### ISSUE TITLE
SAG Mill only takes stone ores

### ISSUE THREAD

**Issue by UbersawMed** [JasonMcRay/InfiTech-1.7#629]
As it seems the SAG Mill from Ender IO can only take Gregtech ores which have stone as a base block, so any ore from the nether, end or from granite can't be processed with the mill. Is this intended behavior or an oversight?

**Comment by JasonMcRay** [comment]
Problem is that there is +/- 100 ores being generated. There are 5 different "subtypes". That is total of 500 ores that would need to be put in manually in the config. Which is A LOT... Will see if we will figure out an easy way on adding this.
No promises

**Comment by UbersawMed** [comment]
Well, it seems like the ores ID is 979:XYYY, where YYY is the number that identifies the ore and X a number from 0 to 5 which identifies the ore base material, so maybe a simple python script could automate the config if I understand correctly.
Even then, thanks for the confirmation!

**Comment by Xavion3** [comment]
The issue is the ores are non-uniform, some ores are gems and some are quartz and some are metal and some are other things and those all need slightly different output formats, add in that some ores have multipliers (lapis should give more output than other gems like diamond) and you quickly need quite a bit of information to work it out. It is possible, it's just going to be a good bit trickier than just grabbing a list from NEI and dumping it through a basic transformation.

**Comment by JasonMcRay** [comment]
Finished: https://github.com/JasonMcRay/InfiTech-1.7/commit/b0679b114a8fc5b6732bf1dc5b5006c7f9beeec2
