### ISSUE TITLE
diamond shard

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#634]
The diamond shard from bees can be crafted 3x3 into 1 diamond or put into a macerator for 1 diamond dust.
You can either get 1 diamond or 9 diamond dust.
4 diamond dust + itnt in the implosion compressor -> 3 INDUSTRIAL diamond (they are better)

**Comment by Xavion3** [comment]
As of the next update the magical bees diamond bee will be disabled, preventing them giving you the diamond shard, this'll mean the only way to obtain the shard afaik will be from the praecantatio infused crop which gives you about 1 in 10 chance of getting a diamond shard each harvest. Combined with diamonds being much easier to obtain with vitreus infused crops being able to get dirty/impure diamond dust from them really doesn't seem like much of a concern, at worst it adds a very, very slow alternative to obtaining graphite than diamond veins.

Assuming my information hasn't been outdated since I last checked in 3.1 anyway.

**Comment by JasonMcRay** [comment]
We are probably not going to do anything in InfiTech about this. As Xavion said, the only way to get shards is via infused crops. and they are slow.

But still it is considered as possible bug. So i will ask Blood if there is something he can do, to fix it in GT
