### ISSUE TITLE
Minecraft MCL displays only 6 mods MC 1.7.10

### ISSUE THREAD

**Issue by lolera222** [JasonMcRay/InfiTech-1.7#674]
Minecraft Coder Pack
Forge Mod Loader
Minecraft Forge
Mobius Core (I enabled it)
Map Writer (appeared after enabling Mobius and Opis)
Opis (I enabled it)

I enabled Mobius and Opis after the first load that showed only 3 mods, MCP, FML, MF. There was no modification to the pack nor any of the files, i just downloaded the master zip and extracter to .minecraft while i had no copy of any file inside the zip in my .minecraft folder.

After reverting the changes, it said Loaded 3 mods

MCP 9.05
FML 7.10.99.99
Minecraft Forge 10.13.4.1614
Minecraft Forge 10.13.4.1566 (same thing happens)

**Comment by JasonMcRay** [comment]
You cant download the full modpack by clicking on download zip. We are storing mods with LFS, so in order to download you must locally clone the repo.

Sometimes with cloning you will need to pull it again, because some files tend to get stuck.

Or just use FTB or Curse launcher, because we are making pack updates weekly so the difference between repo and live is not too different.
