### ISSUE TITLE
xact appears to be crashing the server

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/InfiTech-1.7#684]
#### Issue Description:

Server crash

#### Is the issue happening on server? Client? Both?

Server. Have not tested in SP.

#### Steps to reproduce (if aplicable):

Unsure. I was not online at the time, but I can ask the affected players to stop by and add content to this Issue thread.

#### Modpack Version (Do *not* use "latest"):

3.2.7 (with Hardcore Wither, Mobius Core, and Opis enabled)

Here are three of the nine time the server crashed today. Let me know if you want the remaining six.

http://pastebin.com/zPNvLUp8
http://pastebin.com/1R9tkbxz
http://pastebin.com/LHJKdiBN

**Comment by JasonMcRay** [comment]
Does anyone by any chance have the XACT table connected to AE2 Interface block?  If yea... remove it

**Comment by JasonMcRay** [comment]
All in all... It would be best to have steps to reproduce, if it is indeed AE2 integration, we can simply disable it. If it is something else... That might be a problem (XACT is no longer developed for 1.7)

**Comment by Vliro** [comment]
Afaik it happens due to invalid inventories. It constantly crashed for me, and that was because I had an unrouted transport pipe directly under it. Also, if you cannot really extract(like the output of Steve smelter thingy w/o IO upgrade) it will craft but it will also crash. Those are two things I discovered.

**Comment by JasonMcRay** [comment]
As for the noise.. you will need to endure that.

As for the crash when trying to output from certain blocks causing crash. I would need to get a list of those blocks when you encounter them.

**Comment by Vliro** [comment]
So far I've only encountered it with 2, and that mostly just removing everything around the crafter. While I am not a programmer, perhaps it tries to go after what is contained in the inventory and ignores the check to extract? 

So far only Steve's worktable with smeltery installed and the unrouted transport pipe has crashed for me. The pipe might be in some way an inventory(?) but not a regular one and as such XACT crashes when checking its environment. 

Other than that, I will report whatever I find. You mentioned the AE interface not being a good idea, and that might follow the same principle, since it isn't really a standard inventory(?) XACT cannot handle it.

**Comment by JasonMcRay** [comment]
After some testing and messing around... XACT crashes when it tries to pull items from an inventory that should not really be accessible. like StevesWorkshop Production Table crafting grid. XACT has an option to ignore certain blocks and not pulling items from it, but its currently bugged in a way that only 1 block can be specified in there, only the first one specified in there is being ignored...

So all I recommend is not putting XACT crafter near any other modded Crafting tables.

Oh and AE2 integration seems to work just fine... at least when I tested it yesterday :)
