### ISSUE TITLE
Add more GT Ores to the Native Cluster list?

### ISSUE THREAD

**Issue by TehScrub** [JasonMcRay/InfiTech-1.7#693]
Is there any way we could have more ores added to the Native Cluster list? Witching Gadgets has an integrated way to make a cluster from any ore if it's enabled, all that needs to be done is add it to a list and enable the "allow clusters" option in the config. 

Is this a possibility? I'm quickly find some newfound love for the Pickaxe of the Core, but when mining a Uranium vein and having stacks of pitcheblende and Uranium 238 ore, and then having Uranium 238 Clusters from Uranite ore seems a bit odd

**Comment by TehSekys** [comment]
I honestly think almost every ore could be added to the Native Cluster listing, even if you do lose the ability to process them for certain rare byproducts in some cases. I feel like giving Thaumcraft a little more life could be a good addition to the pack, especially as we do not have KAMI, and lategame the best tool is a Drill from GT, this would encourage continued use of the Pickaxe of the Core ^^

**Comment by Xavion3** [comment]
So one thing is that the clusters are only for metal, that's significant as it's why we don't have clusters for most ores, they're gems or something else that isn't a metal. That's even before you consider a bunch of ores don't have a metal/gem that is their primary product.

You should be getting U238 clusters from U238 ore, remember not a 100% drop rate though so you be getting both some uraninite and uranium 238 ore despite getting clusters from both.

The Witching Gadget config is useless, it's disabled for a reason. It actually generates from an internal whitelist and isn't compatible with GT ores so it generates most of the clusters as a dull grey ignoring ore colour, our custom clusters have everything on it and more. We can add more the same we added everything so far though.

So yeah, if you've got any suggestions that follow the three rules of "Have a primary output", "Primary output is a metal", and "Adding a cluster won't make that higher output than using bees" they can be looked at. Bees with their x4 boost should be higher though, and if you've got an idea for how to make clusters from gem ores work as a thing those might be added as well. Maybe giving a bunch of flawed or chipped gems worth the increased value? That'd make some sense.

**Comment by TehSekys** [comment]
I know there were quite a few metal ores that I did indeed mine over and over thinking that they should drop shards, and they never did. I'd be happy to go through the ore list here in a bit and post a list of what ores I personally think should drop clusters, just based on common sense and guidelines you posted, as those were basically what I used as criteria and why I was surprised that U-238 ore wasn't dropping any clusters.

I'll get a list together here in a bit.

**Comment by TehSekys** [comment]
The ore below smelt into an ingot of some kind, and having a cluster for the same ingot would make sense.

Lithium Ore  - Lithium Cluster
Sheldonite Ore - Platinum Cluster
Pyrite Ore - Iron Cluster
Chalcopyrite Ore - Copper Cluster
Desh Ore - Desh Cluster
Magnesite Ore - Magnesium Cluster
Pentlandite Ore  - Nickel Cluster
Banded Iron - Iron Cluster
Yellow Limonite - Iron Cluster
Pyrolusite Ore - Manganese Cluster
Stibnite Ore - Antimony Cluster

Cassiterite Ore has a Cassiterite Cluster, however it drops a Tin Cluster when mined. Not sure if intended, since Cassiterite Clusters are the output when crucible refining said ore. Uranium 238 Clusters do not drop from Uranium 238, I tested this quite extensively with a Fortune 10 Pickaxe of the Core as well, zero clusters.

For gems, the flawed / chipped thing seems like a good idea. Maybe make a Native Gem Cluster for gem blocks. With a Fortune III pickaxe, the average output of gems ends up being roughly x2.2, so I feel like a Native Gem cluster could be processed in a Sifting Machine for maybe something slightly higher than sifting a purified ore of the same type, considering if you run a gem block through the entire processing, you get two purified ore to run through the sifting machine.

If a purified ore is like this;
1.00% 
4.00% 
15.00%
20.00%
40.00%
50.00%

Then a Native Gem Cluster could easily sift for something like what's below, as it would just be a flat x3 increase on average.

3.00% Exquisite or Gem
12.00% Flawless or Gem
40.00% Gem
60.00% Flawed or Gem
100% Chipped or Gem 
20% Chipped or Gem
100% Dust
50% Dust

**Comment by Xavion3** [comment]
So Lithium wasn't added originally because it's treated differently from the others, not having an ingot form and all. Not overlooked so much as decided against because of that, it could get added though thinking on it.

Yellorite ore was just overlooked too, nothing more complex than that, probably the case with Desh too. Naquadah is fine as mentioned, can't change the mining levels although in theory if you could mine it it should work. Cassiterite giving Tin just looks like a bug that should be fixable, I think it'd only affect stone too, cassiterite in granite should give cassiterite clusters if my theory is correct.

For the rest of the list of metals, I'd have to double check but the main reason things were rejected is not being pure enough. I've actually been going back and forth on removing all non-pure clusters but been inevitably leaning towards leaving them in, although tungstate was nerfed because it was OP and everything else would have to be checked similarly.

For gems I'm not sure, I'll think on it a bit more. Something about it just feels iffy to me as the process seems to be designed for metal. Might just do it for the tiered gem type ones or something.

**Comment by JasonMcRay** [comment]
OK so...
Cassiterite, Uranium 238, Gold, Iron, Copper, etc.... clusters are fixed. They now drop and drop the correct one.

As for the list of the ores you put there @TehScrub decided to go with only 2 ores that can give one type of cluster.

Lithium Ore - Lithium Cluster - YES
Sheldonite Ore - Platinum Cluster - YES
Pyrite Ore - Iron Cluster - NO
Chalcopyrite Ore - Copper Cluster - NO
Desh Ore - Desh Cluster - YES
Magnesite Ore - Magnesium Cluster - YES
Pentlandite Ore - Nickel Cluster - NO
Banded Iron - Iron Cluster - NO
Yellow Limonite - Iron Cluster - NO
Pyrolusite Ore - Manganese Cluster - YES
Stibnite Ore - Antimony Cluster - YES
Bauxite Ore - Aluminium Cluster (could maybe be considered its primary output?) - NO - Its too much inpure ore. Even magic can't easily tell what should be given
Yellorite Ore - Yellorite Cluster (this is basically equivalent to Uranium in the MC universe, so why not?) - YES
Endium Ore - Endium Cluster (it's definitely a metal, not sure if it needs a cluster though. kind of up for debate I suppose) - YES

As for gems: No... Going to keep it in the "just metal"

**Comment by JasonMcRay** [comment]
Little update. Desh and Yellorite... I am unable to make it work...

**Comment by TehScrub** [comment]
I was just tossing ideas out that seemed like they may be a good addition. Anything that gives magic more love and reason to be used in the pack is completely fine by me. Hell, if it has a crucible recipe even if you can't make it work with the pickaxe of the core, that's still completely fine, more Thaumatorium recipes!

**Comment by JasonMcRay** [comment]
Yup.. I wanted to make pack update today, but since I spend few hours trying to make the Desh and Yellorite work with Pickaxe of the Core. I dont think I will be able to make that update....

And I dont want to update without this implemented, since I already done some changes in the pack for this issue... So it would be incomplete. Hopefully the update will be ready during next week.

**Comment by TehScrub** [comment]
Just as an aside to this issue, I noticed that the Excavation Focus with the Dowsing upgrade does not seem to turn anything but vanilla ores into Native Clusters. Not sure if that should be lumped in with this, a separate issue, or if it's not fixable at all.

**Comment by Timeslice42** [comment]
I'd like/expect the Dowsing upgrade to be 1/4-1/2 as effective at finding clusters as the PotC. Does anyone know what the actual chances are on both?
