### ISSUE TITLE
Ram issue

### ISSUE THREAD

**Issue by apexstingray** [JasonMcRay/InfiTech-1.7#720]
I did not change the mod pack. The issue is that when playing the pack, it takes up 5 gb of RAM and makes the game all laggy. I tried playing several other ftb packs and the RAM was fine. I allocated 7 gb of ram to the game too

 I haven't tried on a server but I'm pretty sure it would have Ram issues on a server.

Ram jumps to 5000 mb or 5 Gb and game gets laggy. I tried making several worlds and I reset my computer and the problem still persists.

I expected the Ram usage not to be so high

v3.2.9

[MinecraftLog.txt](https://github.com/JasonMcRay/InfiTech-1.7/files/315478/MinecraftLog.txt)

**Comment by apexstingray** [comment]
HELP :(

**Comment by JasonMcRay** [comment]
Are you using the recomended custom JVM arguments posted on the forum? What are your PC specs? Java version? Latest Graphics drivers?...

**Comment by apexstingray** [comment]
My pc specs are Nvidia gtx 650 and 8 gb of RAM and an i5 @3ghz. My java is up to date and I don't think I'm using the JVM arguments. My drivers are updated too

**Comment by JasonMcRay** [comment]
``-Xmx4G -Xms2G -d64 -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=80 -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+UseCodeCacheFlushing -XX:ParallelGCThreads=4``

Try these JVMs. I personaly had much better performace with these.
To set them on the FTB Launcher:
1) Open Options tab
2) Advanced Options
3) Put it into Additional Java Parameters

Keep in mind that Java will use whatever you will let it to use. So if you have 8GB of RAM, then allocating 7GB is bad, because you will leave only 1GB for your OS. For starting world, not advanced worlds, 4-6GB should be enough.

**Comment by apexstingray** [comment]
so I put those jvms in and set the max ram thing to 4.5 gb and it still is laggy in game and it says its 50 percent memory used :(

**Comment by JasonMcRay** [comment]
Unfortunately this is not entirely pack related. InfiTech 2 is resource heavy, so it cannot be fixed on our side.
