### ISSUE TITLE
[HQM] Change magnetize task to a detect task

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#726]
In the "Steel Age" set the quest "Magnetize" has a task to craft 8 magnetic iron rods. This should be changed to a detect task, for those of us who aren't dumb enough to waste our redstone on magnetizing, or who have access to a redstone vein.

**Comment by JasonMcRay** [comment]
The magnetizing quest if I am not mistaken is before you have any machines to your disposal, so the only way to craft them is by using redstone. If you already have Polarizer, because you either started the quests after you have some machines, or you skipped ahead you can still complete it without waste by magnetizing ingots and crafting the rods with file afterwards.

**Comment by Timeslice42** [comment]
lol, it never even occured to me that I could magnetize an ingot.
