### ISSUE TITLE
Greatwood rod-based thaumcraft scepter seems to be uncraftable

### ISSUE THREAD

**Issue by Divran** [JasonMcRay/InfiTech-1.7#729]
#### Issue Description:
I wanted to make myself a scepter so that I could jar a node (or ten) and move it to my base. I can't make the silverwood rod yet since I can't make stainless steel yet. According to the thaumonomicon, the greatwood rod based scepter requires golden wand caps, and there doesn't seem to be any way to craft those. The research tree goes directly from basic wand crafting -> silver caps -> thaumium caps -> scepter crafting. I can't see any gold wand caps research.
See http://i.imgur.com/TdkHwPm.png

I'm not 100% sure if this is an actual bug or if there's something else I need to research (or some quest to complete) to unlock this. If so, please let me know. Also, why can't I craft a scepter with silver wand caps? Silver wand caps have a better vis cost reduction than gold iirc.

#### Is the issue happening on server? Client? Both?
Tested on a server, and also in single player by unlocking all thaumcraft research using a command. Couldn't craft gold caps in either SP or MP, but it may still have to do with me not completing the quest book.

#### What happens:
Can't craft gold caps, and therefore can't craft greatwood rod-based scepters.

#### What you expected to happen:
Should be able to craft greatwood rod-based scepters.

____
#### Modpack Version (Do *not* use "latest"):
3.2.9

**Comment by Xavion3** [comment]
Ok, so much like normal wands and staffs, you should be able to mix and match caps with wand cores, the gold + greatwood is just the example they give. I suggest trying with silver, if you mean you have actually tried crafting a sceptre with silver caps and it didn't work please specify, because it sounds to me like you're describing an issue with what appears in the thaumonomicon.

Although it might be possible to fix that I suppose, not sure.

**Comment by Divran** [comment]
Ah, yes, of course. you're right. I'll try that.

**Comment by Divran** [comment]
yep it was completely possible to use any wand cap. Why was the gold one disabled, though? Anyway this issue can be closed.
