### ISSUE TITLE
Biomass > Biogas/Ethanol Unification

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#742]
#### Issue Description:
Also please state if you modified the modpack in any way.

If you create Biomass from IC2, in the GT distillation tower it creates Bio-gas. 
BUT
If you create Biomass from Forestry, in the GT distillation tower it creates ethanol. 

Both these are completely different outputs (one gas, one liquid) from basically the same product. Can we unify these so that it doesn't matter that Biomass you use it'll give some of both outputs in the Distillation tower?
I'm currently using the IC2 setup as it's better than the forestry setup, but I'm getting only Biogas where I'd expect both. 

#### Is the issue happening on server? Client? Both?

Both server and client. 

#### What happens:

Two different outputs from basically the same substance...

#### What you expected to happen:

I'd expect you to get both the ethanol liquid on a lower level and biogas above it. 

#### Steps to reproduce (if aplicable):

Just try both types of liquid in the GT Distillation tower.
____
#### Modpack Version (Do *not* use "latest"):

3.2.10.1 - Official Server

#### Your most recent log file where the issue was present: 

Doesn't apply.

**Comment by Timeslice42** [comment]
This is exactly how it's supposed to work. You get IC2 biogas from IC2 biomass and Forestry ethanol from Forestry biomass. That's why jason renamed the IC2 biomass to industrial biomass, to help aleviate the assumption that they're the same thing (which they aren't).

If you want your forestry ethanol production to be any good you need to breed better trees. I like to mix plum and lemon trees, so that you get a high yield of juicy fast growing fruit. Don't forget to also make a tree that's fast growing, with sappy saplings. And finally, make sure that the forestry config isn't set to HARD. We worked out a while ago that it really should be on NORMAL to be in line with IC2/GT energy production.

**Comment by groveham** [comment]
I didn't know that it was intentional, but logically thinking it'd be better if they could be combined to give both outputs from the Forestry method, to give both ethanol and biogas. 

If it's not going to be changed that's fine close this issue :)

**Comment by Timeslice42** [comment]
Why would you want the forestry machines to provide both ethanol and biogas?
