### ISSUE TITLE
food too easy to get (suggestion)

### ISSUE THREAD

**Issue by wtfmynamesarepopular** [JasonMcRay/InfiTech-1.7#813]
hi, i've played Infitech 2 for quite a while now (1+ month playtime) and i'm close to upgrading one of my fusion reactors to tier 3. the only thing i'm missing is a way to use all that energy.
i found a mining shaft very early; the very first time i dug down to level 30 i found one. the first chest contained about 15 "feast" category food items.
because of this, i NEVER had to look for food at all; whenever i got low on food, i found another chest with more food. at some point, i built an ender quarry; that felt like cheating so i stopped using it. got me a huge buffer as well, though. later, i'd just go to the moon or mars for more food... which doesn't feel right ;)
the one thing i never cared to build was some kind of food farm.
please consider nerfing big "feast" type (harvestcraft) foodstuff from chests. either reduce the chance/amount one gets, or spawn weaker food.
thanks, and thanks for the awesome pack!

version: 3.2.15 and earlier

**Comment by codewarrior0** [comment]
Same here. Found about 30 spaghetti, 20 deluxe burgers and 20 epic bacon in mineshaft chests. Currently in the middle of HV tech and haven't had to craft any new food since the beginning. Dunno if we're just lucky finding these rich mineshafts, but some of the Harvestcraft food is definitely a bit strong.
