### ISSUE TITLE
Tungsten Quest Order

### ISSUE THREAD

**Issue by DFliyerz** [JasonMcRay/InfiTech-1.7#819]
In the Nuclear Age quests, the quest where you must obtain Hot Tungsten Ingots comes before the quest where you make Nichrome Coils, but Nichrome is required to get the electric blast furnace hot enough to make tungsten.

**Comment by codewarrior0** [comment]
These quests and the ultimate alloy quests should be moved around a bit, ever since three new ranks of heating coils were added to GT5-U.

Nichrome coils (3600K) allow Tungsten, Tungstensteel, Enderium, and Osmium
Tungstensteel coils (4500K) allow HSS-G, NiobiumTitanium, VanadiumGallium, YttriumBariumCuprate, and Enriched Naquadah
HSS-G Coils (5400K) allow HSS-E, HSS-S, Naquadah
Naquadah coils (7200K) allow Naquadah Alloy
Naquadah Alloy (9001K) coils allow Naquadria

**Comment by Timeslice42** [comment]
There are alot of unneccessary quest requirements... I got Jason to tone down several things in the first quest set, but I basically got tired of the process after that. Not to mention that me and him have differing philosophies on what quest requirements and rewards should look like.

That being said I doubt Jason would object to someone helping him redo the high tier alloy quests to account for the new progression.

**Comment by JasonMcRay** [comment]
Yea... If someone will re-do the higher tier alloy quests and will send me a exported json file fo that quest line, I might take a look and include the changes in.

**Comment by codewarrior0** [comment]
I'm taking a crack at it right now. Hopefully I can figure out how to export it as JSON when I'm done.

**Comment by JasonMcRay** [comment]
/hqm save „Name of the quest line“ (without quotes)

**Comment by codewarrior0** [comment]
It turns out I found a corner case in HQM's JSON import/export feature. Swapping those two quests, and thus their dependencies, causes the Nuclear Age quest set to not be fully loaded the first time it is imported. The Tungsten quest in particular has no requirements and for some reason can't have requirements assigned to it. But there's a way to fix it, and it's boring.

- Load Nuclear Age
- Open the quest book and navigate to Nuclear Age
- Pick the Quest Requirement tool, click on the Naquadah Reactor quest, then shift-click on it to clear its requirements
- Close the Quest Book
- Save HQM Quests
- Close Minecraft and reopen it
- Load Silicon Age
- Load Nuclear Age
- Load Fusion Age

My changes are the same as above, plus a few tweaks to some quest texts that mention heating coils and temperatures.

Submitted for judicious review: https://www.dropbox.com/s/ikoenuvjxheavc4/issue-819-QuestFiles.zip?dl=0

**Comment by codewarrior0** [comment]
Ugh. Loading a quest set from JSON assigns all new quest IDs to the quests, destroying all player progress in those quest sets. Loaded up my SP world after making those changes and had zero progress in those three quest sets.

**Comment by JasonMcRay** [comment]
Yea.. I need to do it manually after all... But the JSON files will help, because I can just copy paste the diffs at least
